name: Deploy Main Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-main:
    uses: ./.github/workflows/deploy-demo.yml
    permissions:
      contents: read
      id-token: write
    with:
      ref: ${{ github.sha }}
      ref_type: commit
      deployment_target: main
      github_environment: demo-main
      terraform_project_name: collaborative-ai-dlc-main
